[build]
target = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]

[env]
CARGO_TARGET_DIR = "bins"
NAVI_PATH = "/opt/brbr/navi/cheats"
NAVI_CONFIG = "opt/brbr/navi/config"